### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by leggiero** [Yavin/symfony-init-controller#1]
Hi,

Thank you to share this bundle.

When running my project with this bundle, I got the following error:

Fatal error: Uncaught exception 'ReflectionException' with message 'Class Yavin\Symfony\Controller\InitControllerSubscriber does not exist' in /var/www/ditudo.com/site/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/RegisterListenersPass.php on line 97

I do the following steps to use the bundle:
- add to composer.json: "yavin/symfony-init-controller": "dev-master",
- php composer.phar update (the code is successful downloaded to vendor/yavin/...)
- added the services block in the config.yml

Question: I need to add the "new Yavin\Symfony\Controller\InitControllerSubscriber()" AppKernel? I tried to, but I got another not found.

**Comment by Yavin** [comment]
@Dudytz 
First off all I want to apologise for the long time of any response from me. I haven't logged on into github for a long time.

This repository has a bug, that have been fixed. If someone experience save error message run command
`composer update yavin/symfony-init-controller`

**Comment by Yavin** [comment]
i forgot to close this, as it was explained
