### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by zogs** [Yavin/symfony-init-controller#2]
It seems to be impossible to redirect from within the init() method, am i wrong ?
return $this->redirectToRoute('some_route'); is ignored.
I am still looking for a workarround...

Thank you for your work,

**Comment by Yavin** [comment]
Hi,
when i creating this i did not think about that `init()` can return response. If you still looking for solutions i have updated this component. If you install `v0.3` it should work.

``` php
public function init(Request $request)
{
    if ($request->get('redirect') == 1) {
        return $this->redirect('http://example.com');
    }
}
```

composer.json:

``` yml
"yavin/symfony-init-controller": "0.3"
```

closing, reopen if something not work

**Comment by zogs** [comment]
Nice, that does the trick !

Thank you

2015-10-30 23:15 GMT+01:00 Yavin notifications@github.com:
